[graph]
all-features = false
no-default-features = false
targets = []

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Unicode-DFS-2016",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[[licenses.clarify]]
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[bans]
allow = []
deny = []
external-default-features = "allow"
highlight = "all"
multiple-versions = "warn"
skip = []
skip-tree = []
wildcards = "allow"
workspace-default-features = "allow"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "warn"
unknown-registry = "warn"

[sources.allow-org]
bitbucket = [""]
github = [""]
gitlab = [""]
